#pragma once

#define SIGMA_MOUSE_BUTTON_1         0
#define SIGMA_MOUSE_BUTTON_2         1
#define SIGMA_MOUSE_BUTTON_3         2
#define SIGMA_MOUSE_BUTTON_4         3
#define SIGMA_MOUSE_BUTTON_5         4
#define SIGMA_MOUSE_BUTTON_6         5
#define SIGMA_MOUSE_BUTTON_7         6
#define SIGMA_MOUSE_BUTTON_8         7
#define SIGMA_MOUSE_BUTTON_LAST      SIGMA_MOUSE_BUTTON_8
#define SIGMA_MOUSE_BUTTON_LEFT      SIGMA_MOUSE_BUTTON_1
#define SIGMA_MOUSE_BUTTON_RIGHT     SIGMA_MOUSE_BUTTON_2
#define SIGMA_MOUSE_BUTTON_MIDDLE    SIGMA_MOUSE_BUTTON_3